server:
  port: ${SERVER_PORT:8090}
spring:
  security:
    oauth2:
      client:
        registration:
          elm-client:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${GRANT_TYPE:authorization_code}
            scope: ${SCOPE:openid}
            provider: idp
        provider:
          idp:
            issuer-uri: ${ISSUER_URI}
